version: '3'

services:
  app:
    build: .
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app:delegated
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      BASE_URL: http://localhost:4000
